from rest_framework.exceptions import ValidationError


class RepoDataValidation(ValidationError):
    pass
